version: "2"
services:
  app:
    image: "node:lts-alpine"
    user: 1000:1000
    working_dir: "/srv"
    volumes:
      - "./:/srv"
    command: ["gatsby", "develop", "--host", "0.0.0.0"]
    environment:
      PATH: "/srv/node_modules/.bin:$PATH"
    ports:
      - 8000:8000
      - 9000:9000
